'use client'; import { useState } from 'react'; import { useRouter } from 'next/navigation'; import { loginRequest, registerRequest } from '@/lib/auth/api'; import { setSession } from '@/lib/auth/storage'; const initialState = { firstName: '', lastName: '', fullName: '', email: '', password: '', phone: '', employeeCode: '', roleId: '', businessUnitId: '' }; export default function RegisterForm() { const router = useRouter(); const [form, setForm] = useState(initialState); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); function updateField(key, value) { setForm(prev => { const next = { ...prev, [key]: value }; if (key === 'firstName' || key === 'lastName') { next.fullName = `${key === 'firstName' ? value : next.firstName} ${key === 'lastName' ? value : next.lastName}`.trim(); } return next; }); } async function handleSubmit(e) { e.preventDefault(); setError(''); setLoading(true); try { const payload = { ...form, fullName: form.fullName || `${form.firstName} ${form.lastName}`.trim() }; await registerRequest(payload); const loginData = await loginRequest({ email: form.email, password: form.password }); setSession({ token: loginData.accessToken, user: loginData.user }); router.replace('/dashboard/portfolio'); } catch (err) { setError(err.message || 'Registration failed'); } finally { setLoading(false); } } return <form className='authForm' onSubmit={handleSubmit}><div className='authGrid'><label className='authLabel'>First name<input className='authInput' value={form.firstName} onChange={e => updateField('firstName', e.target.value)} required /></label><label className='authLabel'>Last name<input className='authInput' value={form.lastName} onChange={e => updateField('lastName', e.target.value)} required /></label></div><label className='authLabel'>Full name<input className='authInput' value={form.fullName} onChange={e => updateField('fullName', e.target.value)} required /></label><div className='authGrid'><label className='authLabel'>Email<input className='authInput' type='email' value={form.email} onChange={e => updateField('email', e.target.value)} required /></label><label className='authLabel'>Password<input className='authInput' type='password' value={form.password} onChange={e => updateField('password', e.target.value)} required /></label></div><div className='authGrid'><label className='authLabel'>Role ID<input className='authInput' value={form.roleId} onChange={e => updateField('roleId', e.target.value)} required /></label><label className='authLabel'>Business Unit ID<input className='authInput' value={form.businessUnitId} onChange={e => updateField('businessUnitId', e.target.value)} required /></label></div>
<div className='authGrid'>
  <label className='authLabel'>
    Employee Code
    <input
      className='authInput'
      value={form.employeeCode}
      onChange={e => updateField('employeeCode', e.target.value)}
      required
    />
  </label>
</div>{error ? <div className='authError'>{error}</div> : null}<button className='authPrimary' type='submit' disabled={loading}>{loading ? 'Creating account...' : 'Register'}</button></form>; }
